let restaurantId = 13;
let avgRating = '3.7/5'
let tags = ['$', 'Breakfast', 'Lunch', 'Dinner']
let days = ['Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat', 'Sun']
let times = ['08:00-16:30', '08:00-16:30', '08:00-16:30', '08:00-16:30', '08:00-16:30', '08:00-16:30', '08:00-16:30']

let comments = [
    {'name': '窮鬼', 'comment': '月底沒錢好去處，土的味道嚐起來不錯'},
    {'name': '💩', 'comment': '土太乾了都沒水分'},
    {'name': '大安區服務業業者', 'comment': '我都晚上偷偷來這邊摘薄荷泡茶'}
]
let newComments = [
    {'name': 'Cypress 1', 'rating': 4, 'comment': 'Generated by cypress test 1'},
    {'name': 'Cypress 2', 'rating': 3, 'comment': 'Generated by cypress test 2'}
]

describe('111-1 WP Hackathon 2 Public Test\n  (45%) Part III - Restaurant Page', () => {
    context('( 5%) 1. Navigate to restaurant page', () => {
        it('( 5%) 1.  | Clicking search block navigates the user to /restaurant/$id', () => {
            cy.visit('localhost:3000')
            cy.get('.searchContainer button').click()
            cy.get('.searchPageContainer').within(() => {
                cy.get(`div[id="${restaurantId}"]`).click()
            })
            cy.get('.infoContainer').within(() => {
                cy.get('h2').contains('長興園藝資材行')
            })
        })
    })
    context('(15%) 2. Restaurant information', () => {
        it('( 5%) 2a. | Query and display the restaurant tags', () => {
            cy.visit('localhost:3000')
            cy.get('.searchContainer button').click()
            cy.get('.searchPageContainer').within(() => {
                cy.get(`div[id="${restaurantId}"]`).click()
            })
            cy.get('.infoContainer').within(() => {
                cy.get('.infoRow').eq(1).children()
                .should('have.length', tags.length)
                .each(($elem, idx) => {
                    cy.wrap($elem).should('have.class', 'tag')
                    .contains(tags[idx])
                })  
            })
        })
        it('( 5%) 2b. | Query, calculate and display the average rating', () => {
            cy.visit('localhost:3000')
            cy.get('.searchContainer button').click()
            cy.get('.searchPageContainer').within(() => {
                cy.get(`div[id="${restaurantId}"]`).click()
            })
            cy.get('.infoContainer').within(() => {
                cy.get('.stars').contains(avgRating)
            })

        })
        it('( 5%) 2c. | Query and display the business time according to the format', () => {
            cy.visit('localhost:3000')
            cy.get('.searchContainer button').click()
            cy.get('.searchPageContainer').within(() => {
                cy.get(`div[id="${restaurantId}"]`).click()
            })
            cy.get('.infoContainer').within(() => {
                cy.get('.businessTime')
                .children()
                .should('have.length', 7)
                .each(($elem, idx) => {
                    cy.wrap($elem).within(() => {
                        cy.get('.day').contains(days[idx])
                        cy.get('.time').contains(times[idx])
                    })
                })
            })
        })
    })
    context('(25%) 3. Comment section', () => {
        it('(10%) 3a. | Query and display the comments on the restaurants', () => {
            cy.visit('localhost:3000')
            cy.get('.searchContainer button').click()
            cy.get('.searchPageContainer').within(() => {
                cy.get(`div[id="${restaurantId}"]`).click()
            })
            cy.get('.comments').children()
            .should('have.length', comments.length)
            .each(($elem, idx) => {
                cy.wrap($elem).within(() => {
                    cy.get('.name').contains(comments[idx].name)
                    cy.get('.content').contains(comments[idx].comment)
                })
            })
        })
        it('(10%) 3b. | New comment is displayed after reloading the page', () => {
            cy.visit('localhost:3000')
            cy.get('.searchContainer button').click()
            cy.get('.searchPageContainer').within(() => {
                cy.get(`div[id="${restaurantId}"]`).click()
            })
            cy.get('.inputContainer').within(() => {
                cy.get('.name').type(newComments[0].name)
                cy.get('.content').type(newComments[0].comment)
                cy.get('span').eq(newComments[0].rating - 1).dblclick()
                cy.get('.submit button').click()
            })
            cy.get('a').click()
            cy.get('.searchContainer button').click()
            cy.get('.searchPageContainer').within(() => {
                cy.get(`div[id="${restaurantId}"]`).click()
            })
            cy.get('.comments').children()
            .should('have.length', comments.length + 1)
            
            cy.get('.comment').eq(comments.length).within(() => {
                cy.get('.name').contains(newComments[0].name)
                cy.get('.content').contains(newComments[0].comment)
            })
        })
        it('( 5%) 3c. | New comment is displayed immediately without reloading the page', () => {
            cy.visit('localhost:3000')
            cy.get('.searchContainer button').click()
            cy.get('.searchPageContainer').within(() => {
                cy.get(`div[id="${restaurantId}"]`).click()
            })
            cy.get('.inputContainer').within(() => {
                cy.get('.name').type(newComments[1].name)
                cy.get('.content').type(newComments[1].comment)
                cy.get('span').eq(newComments[1].rating - 1).dblclick()
                cy.get('.submit button').click()
            })
            cy.get('.comments').children()
            .should('have.length', comments.length + 2)
            
            cy.get('.comment').eq(comments.length+1).within(() => {
                cy.get('.name').contains(newComments[1].name)
                cy.get('.content').contains(newComments[1].comment)
            })
        })
    })
})